# Generated by Django 3.2.13 on 2022-04-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfiles', '0002_auto_20220429_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
